# Exported from Render on 2026-03-25T02:26:10Z
version: "1"
projects:
- name: AeAre Books Site
  environments:
  - name: Production
    services:
    - type: web
      name: aeare-books
      runtime: node
      repo: https://github.com/TIMwilltell/aeare-books
      plan: free
      envVars:
      - key: CONvex_DEPLOYMENT_URL
        sync: false
      region: virginia
      buildCommand: bun install && bun run build
      startCommand: bun build/index.js
      autoDeployTrigger: commit
      previews:
        generation: manual
